---
version: "3.7"
services:
  # https://github.com/haugene/docker-transmission-openvpn
  transmission:
    image: haugene/transmission-openvpn:latest
    container_name: transmission
    restart: always
    ports:
      - "9091:9091"
    # https://haugene.github.io/docker-transmission-openvpn/config-options/
    environment:
      - OPENVPN_PROVIDER=<FILL>
      - OPENVPN_CONFIG=<FILL>
      - OPENVPN_USERNAME=<FILL>
      - OPENVPN_PASSWORD=<FILL>
      - WEBPROXY_ENABLED=false
      - LOCAL_NETWORK=192.168.0.0/16
      - TRANSMISSION_WEB_UI=flood-for-transmission
    volumes:
      - /media/downloads:/data
      - /etc/localtime:/etc/localtime:ro
    cap_add:
      - NET_ADMIN

  # https://github.com/linuxserver/docker-radarr
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: always
    ports:
      - "7878:7878"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /media/radarr:/config
      - /media/movies:/movies
      - /media/downloads/completed:/downloads

  # https://github.com/linuxserver/docker-sonarr
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: always
    ports:
      - "8989:8989"
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /media/sonarr:/config
      - /media/tv:/tv
      - /media/downloads/completed:/downloads

  # https://github.com/linuxserver/docker-prowlarr
  prowlarr:
    image: linuxserver/prowlarr:develop
    container_name: prowlarr
    restart: always
    ports:
      - "9696:9696"
    cap_add:
      - NET_ADMIN
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /media/prowlarr:/config
      - /media/downloads/watch:/downloads  # transmission watch directory

  # https://github.com/dperson/samba
  samba:
    image: dperson/samba:latest
    container_name: samba
    restart: always
    # NOTE: see https://github.com/dperson/samba#troubleshooting
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - "139:139"
      - "445:445"
    environment:
      - USERID=1000
      - GROUPID=1000
      - SHARE=Media;/media
      - TZ=Europe/Amsterdam
    volumes:
      - /media:/media
